name: sist_cgpa
description: "sathyabama CGPA calculator"

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.3+13

environment:
  sdk: ">=3.2.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  flutter_secure_storage: ^9.0.0
  http: ^1.1.2
  top_snackbar_flutter: ^3.1.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  flutter_bloc: ^8.1.3
  sqflite: ^2.3.0
  lottie: ^3.1.2
  flutter_displaymode: ^0.6.0
  google_mobile_ads: ^5.1.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_logo.png"
  min_sdk_android: 16 # android min sdk min:16, default 2

flutter_native_splash:
  color: "#ffffff"
  #background_image: "assets/background.png"
  image: assets/app_splash_screen.png
  android_12:
    image: assets/app_splash_screen.png
    #image: assets/android12splash.png
    color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/database/course_credits.json
    - assets/database/courses.sqlite
    - assets/icons/
    - assets/anim/lottie_anim1.json
    - assets/anim/lottie_anim2.json
    - assets/anim/lottie_anim3.json
    - assets/anim/hat_anim.json

  fonts:
    - family: custom_font
      fonts:
        - asset: assets/fonts/custom_font.otf
